name: Update prices for collection

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:
jobs:
  refresh-prices-japanese-cards:
    name: Refresh prices for Japanese cards in collection
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Refresh prices for Japanese cards in collection
        run: |
          composer install
          bin/console app:tcgc:refresh-japanese-prices Frogfuhrer
      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          git diff --staged --quiet || git commit -m"Updated prices for Japanese cards in collection"
          git push
      - name: ntfy.sh
        uses: robiningelbrecht/ntfy-action@v1.0.0
        if: always()
        with:
            url: ${{ secrets.NTFY_URL }}
            topic: ${{ secrets.NTFY_TOPIC }}
            icon: 'https://github.githubassets.com/images/modules/profile/achievements/starstruck-default.png'
            job_status: ${{ job.status }}

